# -*- coding: utf-8 -*-
"""Bloch Sphere.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FOuaG4O4P5ialuB7a3Na6vZW6wyFG7P7

Use plot_bloch_vector() or plot_bloch_sphere_spherical() to plot a qubit in the states:

|0⟩ 


|1⟩ 


1/√2(|0⟩+|1⟩) 


1/√2(|0⟩−i|1⟩) 



1/√2[i1]
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install qiskit

from qiskit import *
from qiskit.visualization import *

from math import pi, sqrt
coord_1 = [0,0,1]
plot_bloch_vector(coord_1)

coord_2 = [0,0,-1]
plot_bloch_vector(coord_2)

coord_3 = [1,0,0]
plot_bloch_vector(coord_3)

coord_4 = [-1,0,0]
plot_bloch_vector(coord_4)

coord_5 = [1,0,0]
plot_bloch_vector(coord_5)